dependencies:
  - OpenZeppelin/openzeppelin-contracts-upgradeable@4.7.1
compiler:
  solc:
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts-upgradeable@4.7.1"
dotenv: .env
owner:
  addr: ${FEE}
wallets:
  from_key: ${PRIVATE_KEY2}
networks:
  default: development
  rinkeby:
    verify: True
  development:
    verify: False
  ganache-local:
    verify: False
