dotenv: .env
owner:
  addr: ${FEE}
wallets:
  from_key: ${PRIVATE_KEY2}
networks:
  default: development
  rinkeby:
    verify: True
  development:
    verify: False
  ganache-local:
    verify: False
